# Generated by Django 6.0.2 on 2026-07-19 12:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_bus_tracker_token'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='challan',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feeverification',
            name='amount',
            field=models.DecimalField(decimal_places=0, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='transportregistration',
            name='fee_amount',
            field=models.DecimalField(decimal_places=0, default=5000, max_digits=8),
        ),
    ]