# Generated by Django 6.0.2 on 2026-07-19 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0010_alter_challan_amount_alter_feeverification_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='is_off_route',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='last_off_route_alert_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BusLocationPing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_from_route_m', models.FloatField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='location_pings', to='transport.bus')),
            ],
        ),
    ]
