# Generated by Django 6.0.2 on 2026-08-28 22:51

from django.db import migrations, models


def cleanup_duplicate_route_stops(apps, schema_editor):
    RouteStop = apps.get_model('transport', 'RouteStop')
    seen_pairs = set()
    duplicate_ids = []
    for row in RouteStop.objects.order_by('route_id', 'stop_id', 'stop_order', 'id'):
        key = (row.route_id, row.stop_id)
        if key in seen_pairs:
            duplicate_ids.append(row.id)
        else:
            seen_pairs.add(key)
    if duplicate_ids:
        RouteStop.objects.filter(id__in=duplicate_ids).delete()

    for route_id in sorted(RouteStop.objects.values_list('route_id', flat=True).distinct()):
        rows = list(RouteStop.objects.filter(route_id=route_id).order_by('stop_order', 'id'))
        for index, row in enumerate(rows, start=1):
            if row.stop_order != index:
                row.stop_order = index
                row.save(update_fields=['stop_order'])


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0013_incident_occurred_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='routestop',
            options={'ordering': ['route_id', 'stop_order']},
        ),
        migrations.AddField(
            model_name='route',
            name='geometry',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='geometry_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='published', max_length=12),
        ),
        migrations.AddField(
            model_name='stop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='location_accuracy_m',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stop',
            name='location_source',
            field=models.CharField(default='manual', max_length=30),
        ),
        migrations.AddField(
            model_name='stop',
            name='provider_place_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.RunPython(cleanup_duplicate_route_stops, reverse_code=migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop'), name='unique_stop_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.UniqueConstraint(fields=('route', 'stop_order'), name='unique_stop_order_per_route'),
        ),
        migrations.AddConstraint(
            model_name='routestop',
            constraint=models.CheckConstraint(condition=models.Q(('stop_order__gt', 0)), name='route_stop_order_positive'),
        ),
    ]
