# Generated by Django 6.0.2 on 2026-08-31 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0014_alter_routestop_options_route_geometry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrimeRiskZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_id', models.CharField(max_length=80, unique=True)),
                ('geometry', models.JSONField()),
                ('min_latitude', models.FloatField()),
                ('min_longitude', models.FloatField()),
                ('max_latitude', models.FloatField()),
                ('max_longitude', models.FloatField()),
                ('current_score', models.FloatField(blank=True, null=True)),
                ('current_level', models.CharField(default='unclassified', max_length=20)),
                ('confidence', models.CharField(default='none', max_length=20)),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('algorithm_version', models.CharField(default='v1', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['min_latitude', 'max_latitude'], name='transport_c_min_lat_24efb3_idx'), models.Index(fields=['min_longitude', 'max_longitude'], name='transport_c_min_lon_b70897_idx'), models.Index(fields=['current_level'], name='transport_c_current_0e848c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExternalCrimeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_event_id', models.CharField(max_length=180, unique=True)),
                ('source_name', models.CharField(default='external', max_length=120)),
                ('category', models.CharField(max_length=80)),
                ('severity', models.PositiveSmallIntegerField(default=5)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location_precision_m', models.PositiveIntegerField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('source_updated_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['occurred_at'], name='transport_e_occurre_9c3d32_idx'), models.Index(fields=['latitude', 'longitude'], name='transport_e_latitud_1063ec_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrimeRiskSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_days', models.PositiveIntegerField(default=90)),
                ('score', models.FloatField(blank=True, null=True)),
                ('level', models.CharField(default='unclassified', max_length=20)),
                ('confidence', models.CharField(default='none', max_length=20)),
                ('event_count', models.PositiveIntegerField(default=0)),
                ('category_breakdown', models.JSONField(default=dict)),
                ('algorithm_version', models.CharField(default='v1', max_length=30)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='transport.crimeriskzone')),
            ],
            options={
                'indexes': [models.Index(fields=['zone', '-calculated_at'], name='transport_c_zone_id_d919c6_idx')],
            },
        ),
    ]
