# Generated by Django 6.0.2 on 2026-09-04 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0015_crimeriskzone_externalcrimeevent_crimerisksnapshot'),
        ('transport', '0017_semester_transport_fee'),
    ]

    operations = [
    ]
